server.port=8081
spring.application.name=userwrite-ms

spring.jpa.hibernate.ddl-auto=update

# Circuit Breaker

resilience4j.circuitbreaker.instances.userServiceCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.userServiceCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.userServiceCB.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.userServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userServiceCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.userServiceCB.permittedNumberOfCallsInHalfOpenState=2

management.endpoint.circuitbreakers.enabled=true
management.endpoint.circuitbreakerevents.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoint.prometheus.enabled=true