spring.application.name=config-server
server.port=8888

spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///C:/Users/iamsh/Desktop/common-config-repo

logging.level.org.springframework.cloud.config=DEBUG

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true